-- Create skills table
CREATE TABLE public.skills (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  icon TEXT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.skills ENABLE ROW LEVEL SECURITY;

-- Anyone can view skills
CREATE POLICY "Anyone can view skills"
ON public.skills
FOR SELECT
USING (true);

-- Admins can insert skills
CREATE POLICY "Admins can insert skills"
ON public.skills
FOR INSERT
WITH CHECK (has_role(auth.uid(), 'admin'::app_role));

-- Admins can update skills
CREATE POLICY "Admins can update skills"
ON public.skills
FOR UPDATE
USING (has_role(auth.uid(), 'admin'::app_role));

-- Admins can delete skills
CREATE POLICY "Admins can delete skills"
ON public.skills
FOR DELETE
USING (has_role(auth.uid(), 'admin'::app_role));